/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedChatboxProjectIndexRouteImport } from './routes/_authenticated/chatbox/project/index'
import { Route as AuthenticatedChatboxDocumentIndexRouteImport } from './routes/_authenticated/chatbox/document/index'
import { Route as AuthenticatedChatboxProjectNewRouteImport } from './routes/_authenticated/chatbox/project/new'
import { Route as AuthenticatedChatboxDocumentNewRouteImport } from './routes/_authenticated/chatbox/document/new'
import { Route as AuthenticatedChatboxProjectUpdateIdRouteImport } from './routes/_authenticated/chatbox/project/update/$id'
import { Route as AuthenticatedChatboxDocumentUpdateIdRouteImport } from './routes/_authenticated/chatbox/document/update/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatboxProjectIndexRoute =
  AuthenticatedChatboxProjectIndexRouteImport.update({
    id: '/chatbox/project/',
    path: '/chatbox/project/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatboxDocumentIndexRoute =
  AuthenticatedChatboxDocumentIndexRouteImport.update({
    id: '/chatbox/document/',
    path: '/chatbox/document/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatboxProjectNewRoute =
  AuthenticatedChatboxProjectNewRouteImport.update({
    id: '/chatbox/project/new',
    path: '/chatbox/project/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatboxDocumentNewRoute =
  AuthenticatedChatboxDocumentNewRouteImport.update({
    id: '/chatbox/document/new',
    path: '/chatbox/document/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatboxProjectUpdateIdRoute =
  AuthenticatedChatboxProjectUpdateIdRouteImport.update({
    id: '/chatbox/project/update/$id',
    path: '/chatbox/project/update/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatboxDocumentUpdateIdRoute =
  AuthenticatedChatboxDocumentUpdateIdRouteImport.update({
    id: '/chatbox/document/update/$id',
    path: '/chatbox/document/update/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/chatbox/document/new': typeof AuthenticatedChatboxDocumentNewRoute
  '/chatbox/project/new': typeof AuthenticatedChatboxProjectNewRoute
  '/chatbox/document': typeof AuthenticatedChatboxDocumentIndexRoute
  '/chatbox/project': typeof AuthenticatedChatboxProjectIndexRoute
  '/chatbox/document/update/$id': typeof AuthenticatedChatboxDocumentUpdateIdRoute
  '/chatbox/project/update/$id': typeof AuthenticatedChatboxProjectUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/chatbox/document/new': typeof AuthenticatedChatboxDocumentNewRoute
  '/chatbox/project/new': typeof AuthenticatedChatboxProjectNewRoute
  '/chatbox/document': typeof AuthenticatedChatboxDocumentIndexRoute
  '/chatbox/project': typeof AuthenticatedChatboxProjectIndexRoute
  '/chatbox/document/update/$id': typeof AuthenticatedChatboxDocumentUpdateIdRoute
  '/chatbox/project/update/$id': typeof AuthenticatedChatboxProjectUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/chatbox/document/new': typeof AuthenticatedChatboxDocumentNewRoute
  '/_authenticated/chatbox/project/new': typeof AuthenticatedChatboxProjectNewRoute
  '/_authenticated/chatbox/document/': typeof AuthenticatedChatboxDocumentIndexRoute
  '/_authenticated/chatbox/project/': typeof AuthenticatedChatboxProjectIndexRoute
  '/_authenticated/chatbox/document/update/$id': typeof AuthenticatedChatboxDocumentUpdateIdRoute
  '/_authenticated/chatbox/project/update/$id': typeof AuthenticatedChatboxProjectUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errors/$error'
    | '/chatbox/document/new'
    | '/chatbox/project/new'
    | '/chatbox/document'
    | '/chatbox/project'
    | '/chatbox/document/update/$id'
    | '/chatbox/project/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors/$error'
    | '/chatbox/document/new'
    | '/chatbox/project/new'
    | '/chatbox/document'
    | '/chatbox/project'
    | '/chatbox/document/update/$id'
    | '/chatbox/project/update/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/chatbox/document/new'
    | '/_authenticated/chatbox/project/new'
    | '/_authenticated/chatbox/document/'
    | '/_authenticated/chatbox/project/'
    | '/_authenticated/chatbox/document/update/$id'
    | '/_authenticated/chatbox/project/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbox/project/': {
      id: '/_authenticated/chatbox/project/'
      path: '/chatbox/project'
      fullPath: '/chatbox/project'
      preLoaderRoute: typeof AuthenticatedChatboxProjectIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbox/document/': {
      id: '/_authenticated/chatbox/document/'
      path: '/chatbox/document'
      fullPath: '/chatbox/document'
      preLoaderRoute: typeof AuthenticatedChatboxDocumentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbox/project/new': {
      id: '/_authenticated/chatbox/project/new'
      path: '/chatbox/project/new'
      fullPath: '/chatbox/project/new'
      preLoaderRoute: typeof AuthenticatedChatboxProjectNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbox/document/new': {
      id: '/_authenticated/chatbox/document/new'
      path: '/chatbox/document/new'
      fullPath: '/chatbox/document/new'
      preLoaderRoute: typeof AuthenticatedChatboxDocumentNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbox/project/update/$id': {
      id: '/_authenticated/chatbox/project/update/$id'
      path: '/chatbox/project/update/$id'
      fullPath: '/chatbox/project/update/$id'
      preLoaderRoute: typeof AuthenticatedChatboxProjectUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbox/document/update/$id': {
      id: '/_authenticated/chatbox/document/update/$id'
      path: '/chatbox/document/update/$id'
      fullPath: '/chatbox/document/update/$id'
      preLoaderRoute: typeof AuthenticatedChatboxDocumentUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedChatboxDocumentNewRoute: typeof AuthenticatedChatboxDocumentNewRoute
  AuthenticatedChatboxProjectNewRoute: typeof AuthenticatedChatboxProjectNewRoute
  AuthenticatedChatboxDocumentIndexRoute: typeof AuthenticatedChatboxDocumentIndexRoute
  AuthenticatedChatboxProjectIndexRoute: typeof AuthenticatedChatboxProjectIndexRoute
  AuthenticatedChatboxDocumentUpdateIdRoute: typeof AuthenticatedChatboxDocumentUpdateIdRoute
  AuthenticatedChatboxProjectUpdateIdRoute: typeof AuthenticatedChatboxProjectUpdateIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedChatboxDocumentNewRoute: AuthenticatedChatboxDocumentNewRoute,
  AuthenticatedChatboxProjectNewRoute: AuthenticatedChatboxProjectNewRoute,
  AuthenticatedChatboxDocumentIndexRoute:
    AuthenticatedChatboxDocumentIndexRoute,
  AuthenticatedChatboxProjectIndexRoute: AuthenticatedChatboxProjectIndexRoute,
  AuthenticatedChatboxDocumentUpdateIdRoute:
    AuthenticatedChatboxDocumentUpdateIdRoute,
  AuthenticatedChatboxProjectUpdateIdRoute:
    AuthenticatedChatboxProjectUpdateIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
